// Code generated by protoc-gen-go. DO NOT EDIT.
// source: email.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EmailValidateError int32

const (
	EmailValidateError_NO_ERROR                     EmailValidateError = 0
	EmailValidateError_OTHER_ERROR                  EmailValidateError = 1
	EmailValidateError_BAD_EMAIL_FORMAT             EmailValidateError = 2
	EmailValidateError_HOST_DOES_NOT_HAVE_MX        EmailValidateError = 3
	EmailValidateError_MX_HOST_IN_RESERVED_IP_RANGE EmailValidateError = 4
)

var EmailValidateError_name = map[int32]string{
	0: "NO_ERROR",
	1: "OTHER_ERROR",
	2: "BAD_EMAIL_FORMAT",
	3: "HOST_DOES_NOT_HAVE_MX",
	4: "MX_HOST_IN_RESERVED_IP_RANGE",
}
var EmailValidateError_value = map[string]int32{
	"NO_ERROR":                     0,
	"OTHER_ERROR":                  1,
	"BAD_EMAIL_FORMAT":             2,
	"HOST_DOES_NOT_HAVE_MX":        3,
	"MX_HOST_IN_RESERVED_IP_RANGE": 4,
}

func (x EmailValidateError) String() string {
	return proto.EnumName(EmailValidateError_name, int32(x))
}
func (EmailValidateError) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_email_0b959da8eaf075ed, []int{0}
}

type EmailValidateRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmailValidateRequest) Reset()         { *m = EmailValidateRequest{} }
func (m *EmailValidateRequest) String() string { return proto.CompactTextString(m) }
func (*EmailValidateRequest) ProtoMessage()    {}
func (*EmailValidateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_email_0b959da8eaf075ed, []int{0}
}
func (m *EmailValidateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailValidateRequest.Unmarshal(m, b)
}
func (m *EmailValidateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailValidateRequest.Marshal(b, m, deterministic)
}
func (dst *EmailValidateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailValidateRequest.Merge(dst, src)
}
func (m *EmailValidateRequest) XXX_Size() int {
	return xxx_messageInfo_EmailValidateRequest.Size(m)
}
func (m *EmailValidateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailValidateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmailValidateRequest proto.InternalMessageInfo

func (m *EmailValidateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *EmailValidateRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type EmailValidateReply struct {
	Id                   string             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Valid                bool               `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	Canonical            string             `protobuf:"bytes,3,opt,name=canonical,proto3" json:"canonical,omitempty"`
	Error                EmailValidateError `protobuf:"varint,4,opt,name=error,proto3,enum=proto.EmailValidateError" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *EmailValidateReply) Reset()         { *m = EmailValidateReply{} }
func (m *EmailValidateReply) String() string { return proto.CompactTextString(m) }
func (*EmailValidateReply) ProtoMessage()    {}
func (*EmailValidateReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_email_0b959da8eaf075ed, []int{1}
}
func (m *EmailValidateReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailValidateReply.Unmarshal(m, b)
}
func (m *EmailValidateReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailValidateReply.Marshal(b, m, deterministic)
}
func (dst *EmailValidateReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailValidateReply.Merge(dst, src)
}
func (m *EmailValidateReply) XXX_Size() int {
	return xxx_messageInfo_EmailValidateReply.Size(m)
}
func (m *EmailValidateReply) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailValidateReply.DiscardUnknown(m)
}

var xxx_messageInfo_EmailValidateReply proto.InternalMessageInfo

func (m *EmailValidateReply) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *EmailValidateReply) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *EmailValidateReply) GetCanonical() string {
	if m != nil {
		return m.Canonical
	}
	return ""
}

func (m *EmailValidateReply) GetError() EmailValidateError {
	if m != nil {
		return m.Error
	}
	return EmailValidateError_NO_ERROR
}

func init() {
	proto.RegisterType((*EmailValidateRequest)(nil), "proto.EmailValidateRequest")
	proto.RegisterType((*EmailValidateReply)(nil), "proto.EmailValidateReply")
	proto.RegisterEnum("proto.EmailValidateError", EmailValidateError_name, EmailValidateError_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EmailClient is the client API for Email service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EmailClient interface {
	// Validate email
	Validate(ctx context.Context, in *EmailValidateRequest, opts ...grpc.CallOption) (*EmailValidateReply, error)
	//  // Bulk validate email
	//  rpc BulkValidate (BulkEmailValidateRequest) returns (BulkEmailValidateReply) {}
	// Stream validate email
	StreamValidate(ctx context.Context, opts ...grpc.CallOption) (Email_StreamValidateClient, error)
}

type emailClient struct {
	cc *grpc.ClientConn
}

func NewEmailClient(cc *grpc.ClientConn) EmailClient {
	return &emailClient{cc}
}

func (c *emailClient) Validate(ctx context.Context, in *EmailValidateRequest, opts ...grpc.CallOption) (*EmailValidateReply, error) {
	out := new(EmailValidateReply)
	err := c.cc.Invoke(ctx, "/proto.Email/Validate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailClient) StreamValidate(ctx context.Context, opts ...grpc.CallOption) (Email_StreamValidateClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Email_serviceDesc.Streams[0], "/proto.Email/StreamValidate", opts...)
	if err != nil {
		return nil, err
	}
	x := &emailStreamValidateClient{stream}
	return x, nil
}

type Email_StreamValidateClient interface {
	Send(*EmailValidateRequest) error
	Recv() (*EmailValidateReply, error)
	grpc.ClientStream
}

type emailStreamValidateClient struct {
	grpc.ClientStream
}

func (x *emailStreamValidateClient) Send(m *EmailValidateRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *emailStreamValidateClient) Recv() (*EmailValidateReply, error) {
	m := new(EmailValidateReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// EmailServer is the server API for Email service.
type EmailServer interface {
	// Validate email
	Validate(context.Context, *EmailValidateRequest) (*EmailValidateReply, error)
	//  // Bulk validate email
	//  rpc BulkValidate (BulkEmailValidateRequest) returns (BulkEmailValidateReply) {}
	// Stream validate email
	StreamValidate(Email_StreamValidateServer) error
}

func RegisterEmailServer(s *grpc.Server, srv EmailServer) {
	s.RegisterService(&_Email_serviceDesc, srv)
}

func _Email_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailValidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Email/Validate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServer).Validate(ctx, req.(*EmailValidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Email_StreamValidate_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EmailServer).StreamValidate(&emailStreamValidateServer{stream})
}

type Email_StreamValidateServer interface {
	Send(*EmailValidateReply) error
	Recv() (*EmailValidateRequest, error)
	grpc.ServerStream
}

type emailStreamValidateServer struct {
	grpc.ServerStream
}

func (x *emailStreamValidateServer) Send(m *EmailValidateReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *emailStreamValidateServer) Recv() (*EmailValidateRequest, error) {
	m := new(EmailValidateRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Email_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Email",
	HandlerType: (*EmailServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Validate",
			Handler:    _Email_Validate_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamValidate",
			Handler:       _Email_StreamValidate_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "email.proto",
}

func init() { proto.RegisterFile("email.proto", fileDescriptor_email_0b959da8eaf075ed) }

var fileDescriptor_email_0b959da8eaf075ed = []byte{
	// 313 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x90, 0xcf, 0x4e, 0xfa, 0x40,
	0x10, 0xc7, 0xd9, 0x42, 0x7f, 0x81, 0xe1, 0x17, 0x6c, 0x26, 0x98, 0x14, 0xe5, 0x40, 0x38, 0x11,
	0x0f, 0x68, 0xf0, 0xea, 0xa5, 0xa6, 0xab, 0x90, 0xd8, 0xae, 0x99, 0x36, 0x84, 0xdb, 0x66, 0x85,
	0x3d, 0x34, 0x29, 0x14, 0x6b, 0x35, 0xe1, 0x05, 0x4c, 0x7c, 0x08, 0xdf, 0xd5, 0xb0, 0xc5, 0x18,
	0x49, 0x6f, 0x9e, 0x36, 0xf3, 0xfd, 0xb3, 0xfb, 0xd9, 0x81, 0xb6, 0x5e, 0xab, 0x24, 0x1d, 0x6f,
	0xf3, 0xac, 0xc8, 0xd0, 0x36, 0xc7, 0xf0, 0x06, 0xba, 0x7c, 0xaf, 0xce, 0x55, 0x9a, 0xac, 0x54,
	0xa1, 0x49, 0x3f, 0xbf, 0xea, 0x97, 0x02, 0x3b, 0x60, 0x25, 0x2b, 0x97, 0x0d, 0xd8, 0xa8, 0x45,
	0x56, 0xb2, 0xc2, 0x2e, 0xd8, 0xa6, 0xed, 0x5a, 0x46, 0x2a, 0x87, 0xe1, 0x07, 0x03, 0x3c, 0xaa,
	0x6f, 0xd3, 0x5d, 0x55, 0xf9, 0x6d, 0x1f, 0x30, 0xe5, 0x26, 0x95, 0x03, 0xf6, 0xa1, 0xb5, 0x54,
	0x9b, 0x6c, 0x93, 0x2c, 0x55, 0xea, 0xd6, 0x4d, 0xf8, 0x47, 0xc0, 0x4b, 0xb0, 0x75, 0x9e, 0x67,
	0xb9, 0xdb, 0x18, 0xb0, 0x51, 0x67, 0xd2, 0x2b, 0xb1, 0xc7, 0xbf, 0x5e, 0xe3, 0xfb, 0x00, 0x95,
	0xb9, 0x8b, 0xf7, 0x63, 0x16, 0xe3, 0xe2, 0x7f, 0x68, 0x86, 0x42, 0x72, 0x22, 0x41, 0x4e, 0x0d,
	0x4f, 0xa0, 0x2d, 0xe2, 0x29, 0xa7, 0x83, 0xc0, 0xb0, 0x0b, 0xce, 0xad, 0xe7, 0x4b, 0x1e, 0x78,
	0xb3, 0x07, 0x79, 0x27, 0x28, 0xf0, 0x62, 0xc7, 0xc2, 0x1e, 0x9c, 0x4e, 0x45, 0x14, 0x4b, 0x5f,
	0xf0, 0x48, 0x86, 0x22, 0x96, 0x53, 0x6f, 0xce, 0x65, 0xb0, 0x70, 0xea, 0x38, 0x80, 0x7e, 0xb0,
	0x90, 0xc6, 0x9d, 0x85, 0x92, 0x78, 0xc4, 0x69, 0xce, 0x7d, 0x39, 0x7b, 0x94, 0xe4, 0x85, 0xf7,
	0xdc, 0x69, 0x4c, 0x3e, 0x19, 0xd8, 0x06, 0x04, 0x7d, 0x68, 0x7e, 0xc3, 0xe0, 0x79, 0xd5, 0x07,
	0x0e, 0xdb, 0x3e, 0xeb, 0x55, 0x9b, 0xdb, 0x74, 0x37, 0xac, 0x61, 0x08, 0x9d, 0xa8, 0xc8, 0xb5,
	0x5a, 0xff, 0xfd, 0xae, 0x11, 0xbb, 0x62, 0x4f, 0xff, 0x8c, 0x7f, 0xfd, 0x15, 0x00, 0x00, 0xff,
	0xff, 0x67, 0x08, 0xfb, 0x97, 0x0f, 0x02, 0x00, 0x00,
}
