// Code generated by protoc-gen-go. DO NOT EDIT.
// source: phone.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PhoneValidateError int32

const (
	PhoneValidateError_NO_ERROR    PhoneValidateError = 0
	PhoneValidateError_OTHER_ERROR PhoneValidateError = 1
	PhoneValidateError_BAD_FORMAT  PhoneValidateError = 2
)

var PhoneValidateError_name = map[int32]string{
	0: "NO_ERROR",
	1: "OTHER_ERROR",
	2: "BAD_FORMAT",
}
var PhoneValidateError_value = map[string]int32{
	"NO_ERROR":    0,
	"OTHER_ERROR": 1,
	"BAD_FORMAT":  2,
}

func (x PhoneValidateError) String() string {
	return proto.EnumName(PhoneValidateError_name, int32(x))
}
func (PhoneValidateError) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_phone_1c27caa50e99aefd, []int{0}
}

type PhoneValidateRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PhoneValidateRequest) Reset()         { *m = PhoneValidateRequest{} }
func (m *PhoneValidateRequest) String() string { return proto.CompactTextString(m) }
func (*PhoneValidateRequest) ProtoMessage()    {}
func (*PhoneValidateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_phone_1c27caa50e99aefd, []int{0}
}
func (m *PhoneValidateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PhoneValidateRequest.Unmarshal(m, b)
}
func (m *PhoneValidateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PhoneValidateRequest.Marshal(b, m, deterministic)
}
func (dst *PhoneValidateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PhoneValidateRequest.Merge(dst, src)
}
func (m *PhoneValidateRequest) XXX_Size() int {
	return xxx_messageInfo_PhoneValidateRequest.Size(m)
}
func (m *PhoneValidateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PhoneValidateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PhoneValidateRequest proto.InternalMessageInfo

func (m *PhoneValidateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PhoneValidateRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type PhoneValidateReply struct {
	Id                   string             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Valid                bool               `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	Canonical            string             `protobuf:"bytes,3,opt,name=canonical,proto3" json:"canonical,omitempty"`
	Error                PhoneValidateError `protobuf:"varint,4,opt,name=error,proto3,enum=proto.PhoneValidateError" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *PhoneValidateReply) Reset()         { *m = PhoneValidateReply{} }
func (m *PhoneValidateReply) String() string { return proto.CompactTextString(m) }
func (*PhoneValidateReply) ProtoMessage()    {}
func (*PhoneValidateReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_phone_1c27caa50e99aefd, []int{1}
}
func (m *PhoneValidateReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PhoneValidateReply.Unmarshal(m, b)
}
func (m *PhoneValidateReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PhoneValidateReply.Marshal(b, m, deterministic)
}
func (dst *PhoneValidateReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PhoneValidateReply.Merge(dst, src)
}
func (m *PhoneValidateReply) XXX_Size() int {
	return xxx_messageInfo_PhoneValidateReply.Size(m)
}
func (m *PhoneValidateReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PhoneValidateReply.DiscardUnknown(m)
}

var xxx_messageInfo_PhoneValidateReply proto.InternalMessageInfo

func (m *PhoneValidateReply) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PhoneValidateReply) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *PhoneValidateReply) GetCanonical() string {
	if m != nil {
		return m.Canonical
	}
	return ""
}

func (m *PhoneValidateReply) GetError() PhoneValidateError {
	if m != nil {
		return m.Error
	}
	return PhoneValidateError_NO_ERROR
}

func init() {
	proto.RegisterType((*PhoneValidateRequest)(nil), "proto.PhoneValidateRequest")
	proto.RegisterType((*PhoneValidateReply)(nil), "proto.PhoneValidateReply")
	proto.RegisterEnum("proto.PhoneValidateError", PhoneValidateError_name, PhoneValidateError_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PhoneClient is the client API for Phone service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PhoneClient interface {
	// Validate email
	Validate(ctx context.Context, in *PhoneValidateRequest, opts ...grpc.CallOption) (*PhoneValidateReply, error)
	// Stream validate email
	StreamValidate(ctx context.Context, opts ...grpc.CallOption) (Phone_StreamValidateClient, error)
}

type phoneClient struct {
	cc *grpc.ClientConn
}

func NewPhoneClient(cc *grpc.ClientConn) PhoneClient {
	return &phoneClient{cc}
}

func (c *phoneClient) Validate(ctx context.Context, in *PhoneValidateRequest, opts ...grpc.CallOption) (*PhoneValidateReply, error) {
	out := new(PhoneValidateReply)
	err := c.cc.Invoke(ctx, "/proto.Phone/Validate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *phoneClient) StreamValidate(ctx context.Context, opts ...grpc.CallOption) (Phone_StreamValidateClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Phone_serviceDesc.Streams[0], "/proto.Phone/StreamValidate", opts...)
	if err != nil {
		return nil, err
	}
	x := &phoneStreamValidateClient{stream}
	return x, nil
}

type Phone_StreamValidateClient interface {
	Send(*PhoneValidateRequest) error
	Recv() (*PhoneValidateReply, error)
	grpc.ClientStream
}

type phoneStreamValidateClient struct {
	grpc.ClientStream
}

func (x *phoneStreamValidateClient) Send(m *PhoneValidateRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *phoneStreamValidateClient) Recv() (*PhoneValidateReply, error) {
	m := new(PhoneValidateReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PhoneServer is the server API for Phone service.
type PhoneServer interface {
	// Validate email
	Validate(context.Context, *PhoneValidateRequest) (*PhoneValidateReply, error)
	// Stream validate email
	StreamValidate(Phone_StreamValidateServer) error
}

func RegisterPhoneServer(s *grpc.Server, srv PhoneServer) {
	s.RegisterService(&_Phone_serviceDesc, srv)
}

func _Phone_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PhoneValidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhoneServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Phone/Validate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhoneServer).Validate(ctx, req.(*PhoneValidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Phone_StreamValidate_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PhoneServer).StreamValidate(&phoneStreamValidateServer{stream})
}

type Phone_StreamValidateServer interface {
	Send(*PhoneValidateReply) error
	Recv() (*PhoneValidateRequest, error)
	grpc.ServerStream
}

type phoneStreamValidateServer struct {
	grpc.ServerStream
}

func (x *phoneStreamValidateServer) Send(m *PhoneValidateReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *phoneStreamValidateServer) Recv() (*PhoneValidateRequest, error) {
	m := new(PhoneValidateRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Phone_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Phone",
	HandlerType: (*PhoneServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Validate",
			Handler:    _Phone_Validate_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamValidate",
			Handler:       _Phone_StreamValidate_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "phone.proto",
}

func init() { proto.RegisterFile("phone.proto", fileDescriptor_phone_1c27caa50e99aefd) }

var fileDescriptor_phone_1c27caa50e99aefd = []byte{
	// 260 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0xc8, 0xc8, 0xcf,
	0x4b, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x36, 0x5c, 0x22, 0x01,
	0x20, 0xd1, 0xb0, 0xc4, 0x9c, 0xcc, 0x94, 0xc4, 0x92, 0xd4, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2,
	0x12, 0x21, 0x3e, 0x2e, 0xa6, 0xcc, 0x14, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0xa6, 0xcc,
	0x14, 0x21, 0x11, 0x2e, 0xd6, 0xd4, 0xdc, 0xc4, 0xcc, 0x1c, 0x09, 0x26, 0xb0, 0x10, 0x84, 0xa3,
	0xd4, 0xc9, 0xc8, 0x25, 0x84, 0xa6, 0xbd, 0x20, 0xa7, 0x12, 0x9b, 0xe6, 0x32, 0x90, 0x02, 0xb0,
	0x66, 0x8e, 0x20, 0x08, 0x47, 0x48, 0x86, 0x8b, 0x33, 0x39, 0x31, 0x2f, 0x3f, 0x2f, 0x33, 0x39,
	0x31, 0x47, 0x82, 0x19, 0xac, 0x18, 0x21, 0x20, 0xa4, 0xcf, 0xc5, 0x9a, 0x5a, 0x54, 0x94, 0x5f,
	0x24, 0xc1, 0xa2, 0xc0, 0xa8, 0xc1, 0x67, 0x24, 0x09, 0x71, 0xb6, 0x1e, 0x8a, 0x6d, 0xae, 0x20,
	0x05, 0x41, 0x10, 0x75, 0x5a, 0xce, 0x68, 0x4e, 0x01, 0x4b, 0x0a, 0xf1, 0x70, 0x71, 0xf8, 0xf9,
	0xc7, 0xbb, 0x06, 0x05, 0xf9, 0x07, 0x09, 0x30, 0x08, 0xf1, 0x73, 0x71, 0xfb, 0x87, 0x78, 0xb8,
	0x06, 0x41, 0x05, 0x18, 0x85, 0xf8, 0xb8, 0xb8, 0x9c, 0x1c, 0x5d, 0xe2, 0xdd, 0xfc, 0x83, 0x7c,
	0x1d, 0x43, 0x04, 0x98, 0x8c, 0xe6, 0x32, 0x72, 0xb1, 0x82, 0x4d, 0x11, 0x72, 0xe1, 0xe2, 0x80,
	0x99, 0x24, 0x24, 0x8d, 0xcd, 0x72, 0x68, 0x48, 0x49, 0x49, 0x62, 0x97, 0x2c, 0xc8, 0xa9, 0x54,
	0x62, 0x10, 0xf2, 0xe3, 0xe2, 0x0b, 0x2e, 0x29, 0x4a, 0x4d, 0xcc, 0xa5, 0xdc, 0x2c, 0x0d, 0x46,
	0x03, 0xc6, 0x24, 0x36, 0xb0, 0xbc, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xbb, 0xf9, 0x9f, 0x14,
	0xcb, 0x01, 0x00, 0x00,
}
