// Code generated by protoc-gen-go. DO NOT EDIT.
// source: phone.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PhoneValidateError int32

const (
	PhoneValidateError_NO_ERROR                                            PhoneValidateError = 0
	PhoneValidateError_OTHER_ERROR                                         PhoneValidateError = 1
	PhoneValidateError_DONT_KNOW_COUNTRY_CODE                              PhoneValidateError = 2
	PhoneValidateError_DONT_KNOW_PHONE                                     PhoneValidateError = 3
	PhoneValidateError_WRONG_LENGHT_NUMBER                                 PhoneValidateError = 4
	PhoneValidateError_CODE_NOT_FOUND_FOR_RUSSIAN_DATABASE                 PhoneValidateError = 5
	PhoneValidateError_NUMBER_NOT_FOUND_IN_CODE_RANGE_FOR_RUSSIAN_DATABASE PhoneValidateError = 6
)

var PhoneValidateError_name = map[int32]string{
	0: "NO_ERROR",
	1: "OTHER_ERROR",
	2: "DONT_KNOW_COUNTRY_CODE",
	3: "DONT_KNOW_PHONE",
	4: "WRONG_LENGHT_NUMBER",
	5: "CODE_NOT_FOUND_FOR_RUSSIAN_DATABASE",
	6: "NUMBER_NOT_FOUND_IN_CODE_RANGE_FOR_RUSSIAN_DATABASE",
}
var PhoneValidateError_value = map[string]int32{
	"NO_ERROR":                            0,
	"OTHER_ERROR":                         1,
	"DONT_KNOW_COUNTRY_CODE":              2,
	"DONT_KNOW_PHONE":                     3,
	"WRONG_LENGHT_NUMBER":                 4,
	"CODE_NOT_FOUND_FOR_RUSSIAN_DATABASE": 5,
	"NUMBER_NOT_FOUND_IN_CODE_RANGE_FOR_RUSSIAN_DATABASE": 6,
}

func (x PhoneValidateError) String() string {
	return proto.EnumName(PhoneValidateError_name, int32(x))
}
func (PhoneValidateError) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_phone_66dcd7a9f70eb176, []int{0}
}

type PhoneValidateRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Number               string   `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PhoneValidateRequest) Reset()         { *m = PhoneValidateRequest{} }
func (m *PhoneValidateRequest) String() string { return proto.CompactTextString(m) }
func (*PhoneValidateRequest) ProtoMessage()    {}
func (*PhoneValidateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_phone_66dcd7a9f70eb176, []int{0}
}
func (m *PhoneValidateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PhoneValidateRequest.Unmarshal(m, b)
}
func (m *PhoneValidateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PhoneValidateRequest.Marshal(b, m, deterministic)
}
func (dst *PhoneValidateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PhoneValidateRequest.Merge(dst, src)
}
func (m *PhoneValidateRequest) XXX_Size() int {
	return xxx_messageInfo_PhoneValidateRequest.Size(m)
}
func (m *PhoneValidateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PhoneValidateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PhoneValidateRequest proto.InternalMessageInfo

func (m *PhoneValidateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PhoneValidateRequest) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

type PhoneValidateReply struct {
	Id                   string             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Valid                bool               `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	Canonical            string             `protobuf:"bytes,3,opt,name=canonical,proto3" json:"canonical,omitempty"`
	Provider             string             `protobuf:"bytes,4,opt,name=provider,proto3" json:"provider,omitempty"`
	Error                PhoneValidateError `protobuf:"varint,5,opt,name=error,proto3,enum=proto.PhoneValidateError" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *PhoneValidateReply) Reset()         { *m = PhoneValidateReply{} }
func (m *PhoneValidateReply) String() string { return proto.CompactTextString(m) }
func (*PhoneValidateReply) ProtoMessage()    {}
func (*PhoneValidateReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_phone_66dcd7a9f70eb176, []int{1}
}
func (m *PhoneValidateReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PhoneValidateReply.Unmarshal(m, b)
}
func (m *PhoneValidateReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PhoneValidateReply.Marshal(b, m, deterministic)
}
func (dst *PhoneValidateReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PhoneValidateReply.Merge(dst, src)
}
func (m *PhoneValidateReply) XXX_Size() int {
	return xxx_messageInfo_PhoneValidateReply.Size(m)
}
func (m *PhoneValidateReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PhoneValidateReply.DiscardUnknown(m)
}

var xxx_messageInfo_PhoneValidateReply proto.InternalMessageInfo

func (m *PhoneValidateReply) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PhoneValidateReply) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *PhoneValidateReply) GetCanonical() string {
	if m != nil {
		return m.Canonical
	}
	return ""
}

func (m *PhoneValidateReply) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *PhoneValidateReply) GetError() PhoneValidateError {
	if m != nil {
		return m.Error
	}
	return PhoneValidateError_NO_ERROR
}

func init() {
	proto.RegisterType((*PhoneValidateRequest)(nil), "proto.PhoneValidateRequest")
	proto.RegisterType((*PhoneValidateReply)(nil), "proto.PhoneValidateReply")
	proto.RegisterEnum("proto.PhoneValidateError", PhoneValidateError_name, PhoneValidateError_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PhoneClient is the client API for Phone service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PhoneClient interface {
	// Validate phone
	Validate(ctx context.Context, in *PhoneValidateRequest, opts ...grpc.CallOption) (*PhoneValidateReply, error)
	// Stream validate phone
	StreamValidate(ctx context.Context, opts ...grpc.CallOption) (Phone_StreamValidateClient, error)
}

type phoneClient struct {
	cc *grpc.ClientConn
}

func NewPhoneClient(cc *grpc.ClientConn) PhoneClient {
	return &phoneClient{cc}
}

func (c *phoneClient) Validate(ctx context.Context, in *PhoneValidateRequest, opts ...grpc.CallOption) (*PhoneValidateReply, error) {
	out := new(PhoneValidateReply)
	err := c.cc.Invoke(ctx, "/proto.Phone/Validate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *phoneClient) StreamValidate(ctx context.Context, opts ...grpc.CallOption) (Phone_StreamValidateClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Phone_serviceDesc.Streams[0], "/proto.Phone/StreamValidate", opts...)
	if err != nil {
		return nil, err
	}
	x := &phoneStreamValidateClient{stream}
	return x, nil
}

type Phone_StreamValidateClient interface {
	Send(*PhoneValidateRequest) error
	Recv() (*PhoneValidateReply, error)
	grpc.ClientStream
}

type phoneStreamValidateClient struct {
	grpc.ClientStream
}

func (x *phoneStreamValidateClient) Send(m *PhoneValidateRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *phoneStreamValidateClient) Recv() (*PhoneValidateReply, error) {
	m := new(PhoneValidateReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PhoneServer is the server API for Phone service.
type PhoneServer interface {
	// Validate phone
	Validate(context.Context, *PhoneValidateRequest) (*PhoneValidateReply, error)
	// Stream validate phone
	StreamValidate(Phone_StreamValidateServer) error
}

func RegisterPhoneServer(s *grpc.Server, srv PhoneServer) {
	s.RegisterService(&_Phone_serviceDesc, srv)
}

func _Phone_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PhoneValidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhoneServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Phone/Validate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhoneServer).Validate(ctx, req.(*PhoneValidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Phone_StreamValidate_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PhoneServer).StreamValidate(&phoneStreamValidateServer{stream})
}

type Phone_StreamValidateServer interface {
	Send(*PhoneValidateReply) error
	Recv() (*PhoneValidateRequest, error)
	grpc.ServerStream
}

type phoneStreamValidateServer struct {
	grpc.ServerStream
}

func (x *phoneStreamValidateServer) Send(m *PhoneValidateReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *phoneStreamValidateServer) Recv() (*PhoneValidateRequest, error) {
	m := new(PhoneValidateRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Phone_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Phone",
	HandlerType: (*PhoneServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Validate",
			Handler:    _Phone_Validate_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamValidate",
			Handler:       _Phone_StreamValidate_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "phone.proto",
}

func init() { proto.RegisterFile("phone.proto", fileDescriptor_phone_66dcd7a9f70eb176) }

var fileDescriptor_phone_66dcd7a9f70eb176 = []byte{
	// 378 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x51, 0x4f, 0x6f, 0xd3, 0x30,
	0x14, 0x9f, 0xb3, 0xa5, 0xca, 0xde, 0x50, 0x17, 0xbd, 0x4d, 0x23, 0x2b, 0x1c, 0xa6, 0x72, 0xa0,
	0xe2, 0x30, 0xd0, 0x76, 0xe0, 0x86, 0x94, 0x2d, 0x5e, 0x5b, 0x01, 0x76, 0xe5, 0x24, 0x54, 0x9c,
	0xac, 0xb4, 0xb1, 0x44, 0xa4, 0x34, 0x09, 0x26, 0xad, 0xd4, 0x0f, 0xc3, 0x91, 0xcf, 0xc5, 0x57,
	0x41, 0x71, 0x0a, 0x85, 0xd2, 0xdb, 0x4e, 0xd6, 0xef, 0xdf, 0xf3, 0xfb, 0xd9, 0x70, 0x52, 0x7d,
	0x29, 0x0b, 0x75, 0x5d, 0xe9, 0xb2, 0x2e, 0xd1, 0x36, 0x47, 0xff, 0x1d, 0x9c, 0x4f, 0x1a, 0xf6,
	0x53, 0x92, 0x67, 0x69, 0x52, 0x2b, 0xa1, 0xbe, 0x2e, 0xd5, 0xb7, 0x1a, 0xbb, 0x60, 0x65, 0xa9,
	0x47, 0xae, 0xc8, 0xe0, 0x58, 0x58, 0x59, 0x8a, 0x17, 0xd0, 0x29, 0x96, 0x8b, 0x99, 0xd2, 0x9e,
	0x65, 0xb8, 0x0d, 0xea, 0xff, 0x20, 0x80, 0x3b, 0x03, 0xaa, 0x7c, 0xfd, 0x5f, 0xfc, 0x1c, 0xec,
	0x55, 0x63, 0x30, 0x69, 0x47, 0xb4, 0x00, 0x9f, 0xc3, 0xf1, 0x3c, 0x29, 0xca, 0x22, 0x9b, 0x27,
	0xb9, 0x77, 0x68, 0xcc, 0x5b, 0x02, 0x7b, 0xe0, 0x54, 0xba, 0x5c, 0x65, 0xa9, 0xd2, 0xde, 0x91,
	0x11, 0xff, 0x60, 0x7c, 0x0d, 0xb6, 0xd2, 0xba, 0xd4, 0x9e, 0x7d, 0x45, 0x06, 0xdd, 0x9b, 0xcb,
	0xb6, 0xd4, 0xf5, 0x3f, 0x9b, 0xd0, 0xc6, 0x20, 0x5a, 0xdf, 0xab, 0x9f, 0xbb, 0x7b, 0x1a, 0x15,
	0x9f, 0x80, 0xc3, 0xb8, 0xa4, 0x42, 0x70, 0xe1, 0x1e, 0xe0, 0x29, 0x9c, 0xf0, 0x68, 0x44, 0xc5,
	0x86, 0x20, 0xd8, 0x83, 0x8b, 0x80, 0xb3, 0x48, 0xbe, 0x67, 0x7c, 0x2a, 0xef, 0x79, 0xcc, 0x22,
	0xf1, 0x59, 0xde, 0xf3, 0x80, 0xba, 0x16, 0x9e, 0xc1, 0xe9, 0x56, 0x9b, 0x8c, 0x38, 0xa3, 0xee,
	0x21, 0x3e, 0x85, 0xb3, 0xa9, 0xe0, 0x6c, 0x28, 0x3f, 0x50, 0x36, 0x1c, 0x45, 0x92, 0xc5, 0x1f,
	0xef, 0xa8, 0x70, 0x8f, 0xf0, 0x25, 0xbc, 0x68, 0x72, 0x92, 0xf1, 0x48, 0x3e, 0xf0, 0x98, 0x05,
	0xf2, 0x81, 0x0b, 0x29, 0xe2, 0x30, 0x1c, 0xfb, 0x4c, 0x06, 0x7e, 0xe4, 0xdf, 0xf9, 0x21, 0x75,
	0x6d, 0x7c, 0x0b, 0xb7, 0x6d, 0xe8, 0x2f, 0xeb, 0x98, 0x99, 0x4b, 0xa5, 0xf0, 0xd9, 0x90, 0xee,
	0x0f, 0x76, 0x6e, 0xbe, 0x13, 0xb0, 0x4d, 0x43, 0x0c, 0xc0, 0xf9, 0xdd, 0x12, 0x9f, 0xed, 0x7b,
	0x99, 0xcd, 0x27, 0xf7, 0x2e, 0xf7, 0x8b, 0x55, 0xbe, 0xee, 0x1f, 0x20, 0x83, 0x6e, 0x58, 0x6b,
	0x95, 0x2c, 0x1e, 0x3f, 0x6b, 0x40, 0xde, 0x90, 0x59, 0xc7, 0xe8, 0xb7, 0xbf, 0x02, 0x00, 0x00,
	0xff, 0xff, 0xcf, 0x0f, 0x79, 0xa7, 0x86, 0x02, 0x00, 0x00,
}
